<div class="page_container forgot_container">
    <div class="form-container reveal">
        <form method="post">
            <h3 class="forgot_title">Entrez votre email pour réinitialiser le mot de passe</h3>
            <span class='formSucces'><?php if(isset ($succes)){echo $succes;}?></span><br/>
            <span class='formErrors'><?php if(isset ($errors)){echo $errors;}?></span><br/>
            <input type="email" name="email" class="inputs" required><br/>
            <input type="submit" class="inputs" value="Envoyer l'email">
        </form>
    </div>
</div>


