<!doctype html>
<html>
<head>
<meta charset="UTF8 sans BOM">
<meta name="viewport" content="width=device-width, maximum-scale=1">
<title>Onixia</title>
<!-- CSS  -->
<link href="css/style.css" rel="stylesheet" type="text/css">
</head>
<body>


  <main>
    <?php require $page ?>
  </main>
  <!-- Scripts -->
  <script defer src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script defer src="./js/app.js" ></script>
  <!-- ©Copyright Aïna LAGRANDE  -->
</body>
</html>

